### ISSUE TITLE
Usage of [string containsString:@"rgb"] means you must use iOS 8+

### ISSUE THREAD

**Issue by MKevin3** [jmenter/JAMSVGImage#11]
I want to use this in iOS 7 but usage of [string containsString:@"rgb"] means containsString is not yet available. Maybe you could use a util method to do that instead of requiring iOS 8. Maybe there are other areas that need iOS 8 as well.

**Comment by jmenter** [comment]
Thanks for pointing this out!

I've added a fix, it's in the current develop branch. It will be in the next release as well.
