### ISSUE TITLE
I come from china

### ISSUE THREAD

**Issue by weihaigang** [jmenter/JAMSVGImage#12]
I operate in the inside of the Xib when the compiler can perform wrong but I would like to ask how to solve the two error.

 error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)
 error: IB Designables: Failed to render instance of JAMSVGButton: Failed to load designables from path (null)

**Comment by jmenter** [comment]
Hi, did you install this using Cocoapods? What version of Xcode are you using?

**Comment by weihaigang** [comment]
I installed cocoapods? I used the Xcode version 6.1.1

**Comment by weihaigang** [comment]
I have installed the cocoapods I used the Xcode version is 6.1.1

**Comment by jmenter** [comment]
If you've pulled this in through cocoapods, the IBInspectable and IBDesignable components won't work without a huge amount of hackery.

What you should do is this: drag the class files directly into your project and have your project link to the "lib.dylib" library. You should then be able to see your SVGs in the interface builder portion of Xcode.

Let me know if that works and I'll close this issue.
