### ISSUE TITLE
Please support the svg 1.1 specifications: svg images are not displayed correctly

### ISSUE THREAD

**Issue by Emasoft** [jmenter/JAMSVGImage#13]
This library would be very useful but please support the svg 1.1 specifications: all svg images I tried are not displayed correctly. In this incomplete state the library is not usable. Please finish the excellent work that you have started.

**Comment by Emasoft** [comment]
This is how it should look:
![ios_app_buttons](https://cloud.githubusercontent.com/assets/713559/5924670/d56b48a0-a65d-11e4-95b4-7377a6b7eda9.png)


You can download the original svg file from my google drive (click on the download button):
http://goo.gl/m7TbmM

**Comment by jmenter** [comment]
Yeah, this library only supports a subset of the SVG1.1 spec, just "path" elements and whatever styling information that can be gathered from the file.

Your example SVG has text and filters applied to elements which are not supported now but maybe in the future.

**Comment by Emasoft** [comment]
Supporting only a subset of the svg specs it is like not supporting svg at all. Please fix this.

**Comment by jmenter** [comment]
The people who are using this in production apps would disagree with your assessment. You're welcome to fork and fix whatever deficiencies you think it has.
