### ISSUE TITLE
How to cache JAMSVGImage into disk

### ISSUE THREAD

**Issue by LeeRHuang** [jmenter/JAMSVGImage#26]
this issue has troubled me for some time。i hava to store svg because such svg resource are loaded form netWork,but i find that if i archiver svg into data,read data from disk  transform to svg,it cost some time to render svg。so i change other method ,i want to archiver JAMSVGImage instance ,but what i stuck in is that i can't find any way to archiver JAMSVGImage。now  i just cache JAMSVGImage into memory with singleton,but as all wo know,every time when the app has kiiled or stop running background ,we lost the cache data in  singleton,so i need you help to slove this issus,thanks!

**Comment by jmenter** [comment]
You want to be able to archive JAMSVGImage objects? You'll need to make all classes conform to NSCoding. I suppose you could do this in a set of categories but the best option would be to fork, make your changes, and issue a pull request.

**Comment by jmenter** [comment]
Or, I just implemented this in the develop branch. Use NSKeyedArchiver and NSKeyedUnarchiver to serialize/deserialize JAMSVGImage objects.
