### ISSUE TITLE
Too thin lines in some SVG images

### ISSUE THREAD

**Issue by Jeehut** [jmenter/JAMSVGImage#35]
I'm using this framework since a while and recently some of my SVG images started rendering incorrectly. Specifically lines drawn within SVG images which had been say 5 pixels in width are now 1 pixel in width only. I could track the issue down to the changes made within this pull request: https://github.com/jmenter/JAMSVGImage/pull/27

Maybe @AlexandrGraschenkov knows what the issue could be? Something near adding the stroke in `JAMStyledBezierPath.m` perhaps?

**Comment by AlexandrGraschenkov** [comment]
Can you send example of SVG?

**Comment by Jeehut** [comment]
There you go:
[RoundedRectWithLines.svg.zip](https://github.com/jmenter/JAMSVGImage/files/90072/RoundedRectWithLines.svg.zip)

**Comment by Jeehut** [comment]
Any progress here?

**Comment by AlexandrGraschenkov** [comment]
https://github.com/jmenter/JAMSVGImage/pull/36

**Comment by Jeehut** [comment]
Thanks @AlexandrGraschenkov! @jmenter Could we merge?
