### ISSUE TITLE
NSArray error

### ISSUE THREAD

**Issue by morteza2128** [jmenter/JAMSVGImage#8]
reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
![screen shot 2015-01-05 at 4 51 07 pm](https://cloud.githubusercontent.com/assets/3517532/5613550/2f0c83f2-94fb-11e4-93c4-04a4c6683921.png)

**Comment by jmenter** [comment]
Do you have the svg this crashed with?

**Comment by jmenter** [comment]
the apple.svgz example wasn't gunzipping correctly. I've swapped it out and it works now, need to investigate this.

**Comment by telvin** [comment]
I got the same issue with @morteza2128. XCode builds OK but always crash at the Appdelegate 
Here is my SVG

https://signsmart.com/prod/uploads/systemresources/image-oxvpipm-1356026706.svg

The code:

```
if let svgContent = JAMSVGImage(SVGData: NSData(contentsOfURL: url)){
                            self.svgImageView.svgImage = svgContent
                        }
```

Debug log

> 0   CoreFoundation                      0x000000010511aff5 **exceptionPreprocess + 165
>   1   libobjc.A.dylib                     0x0000000104898deb objc_exception_throw + 48
>   2   CoreFoundation                      0x0000000104fe1a55 -[__NSArrayM insertObject:atIndex:] + 901
>   3   JAMSVGImage                         0x0000000103fab3e6 -[JAMSVGGradient drawInContext:] + 614
>   4   JAMSVGImage                         0x0000000103f9f4b4 -[JAMStyledBezierPath drawStyledPathInContext:] + 1092
>   5   JAMSVGImage                         0x0000000103fad674 -[JAMSVGImage drawInContext:] + 756
>   6   JAMSVGImage                         0x0000000103fad9a4 -[JAMSVGImage drawInRect:inContext:] + 228
>   7   JAMSVGImage                         0x0000000103fae791 -[JAMSVGImageView drawRect:] + 241
>   8   UIKit                               0x0000000105894eb8 -[UIView(CALayerDelegate) drawLayer:inContext:] + 495
>   9   QuartzCore                          0x0000000104181153 -[CALayer drawInContext:] + 257
>   10  QuartzCore                          0x000000010407634d CABackingStoreUpdate_ + 2688
>   11  QuartzCore                          0x0000000104180fd2 ___ZN2CA5Layer8display_Ev_block_invoke + 59
>   12  QuartzCore                          0x0000000104180e50 _ZN2CA5Layer8display_Ev + 1460
>   13  QuartzCore                          0x0000000104175c39 _ZN2CA5Layer17display_if_neededEPNS_11TransactionE + 293
>   14  QuartzCore                          0x0000000104175cc9 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 35
>   15  QuartzCore                          0x000000010416a445 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
>   16  QuartzCore                          0x0000000104197bda _ZN2CA11Transaction6commitEv + 486
>   17  QuartzCore                          0x000000010419834c _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
>   18  CoreFoundation                      0x00000001050464f7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 23
>   19  CoreFoundation                      0x0000000105046467 __CFRunLoopDoObservers + 391
>   20  CoreFoundation                      0x000000010503c0bb __CFRunLoopRun + 1147
>   21  CoreFoundation                      0x000000010503b9b8 CFRunLoopRunSpecific + 488
>   22  GraphicsServices                    0x000000010b5c4ad2 GSEventRunModal + 161
>   23  UIKit                               0x00000001057de8fc UIApplicationMain + 171
>   24  ss-tvapp                            0x00000001039ed42d main + 109
>   25  libdyld.dylib                       0x00000001076df9e9 start + 1
>   26  ???                                 0x0000000000000001 0x0 + 1

The code is failed at the line

`[colors addObject:(id)stop.color.CGColor];`

stop.color is nil.

in the below part:

```
- (void)drawInContext:(CGContextRef)context
{
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    NSMutableArray *colors = NSMutableArray.new;
    CGFloat locations[self.colorStops.count];
    for (JAMSVGGradientColorStop *stop in self.colorStops) {
        [colors addObject:(id)stop.color.CGColor];
        CGFloat location = ((JAMSVGGradientColorStop *)self.colorStops[[self.colorStops indexOfObject:stop]]).position;
        locations[[self.colorStops indexOfObject:stop]] = location;
    }

```
